"use client";
import { useState } from "react";
import Input from "@/components/ui/Input";

export default function Component() {
  const [localConvo, setLocalConvo] = useState<string[]>([]);
  const [userInput, setUserInput] = useState<string>("");
  return (
    <div className="flex h-screen bg-gray-100">
      <aside className="w-1/5 overflow-y-auto bg-[#1a1b26] text-white"></aside>

      <div className="flex flex-col flex-grow">
        <main className="overflow-y-auto p-6 space-y-4 flex-grow bg-[#414868] text-[#2ac3de]">
          {localConvo.map((input, i) => (
            <>{i % 2 === 0 ? <p>user: {input}</p> : <p>Ai: {input}</p>}</>
          ))}
        </main>

        <footer className="p-6 bg-[#24283b]">
          <div className="flex items-center gap-3">
            <img
              src="/micon.svg.png"
              alt="Microphone"
              className="ml-2 h-8 w-8"
              style={{ cursor: "pointer" }}
            />
            <div className="flex-grow flex items-center">
              <input
                className="rounded-lg bg-[#9aa5ce] text-[#24283b] py-4 px-2 w-[100%] h-[50px] placeholder:text-[#24283b]"
                placeholder="Message Adviser"
                onChange={(e) => setUserInput(e.target.value)}
                value={userInput}
              />
            </div>

            <button
              type="submit"
              className="bg-green-600 hover:bg-green-700 text-white rounded-lg px-6 py-2"
              onClick={() => {
                setLocalConvo([
                  ...localConvo,
                  userInput,
                  "This is generated by AI",
                ]);
                setUserInput("");
              }}
            >
              Send
            </button>
          </div>
        </footer>
      </div>
    </div>
  );
}
